# Site settings
title: OSRS Drops

# User settings
project_name: OSRS Drops

url: "https://terjerusska.github.io/osrs-drops"

collections:
  item:
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: "default"

exclude: ['package.json', 'src' , 'node_modules']
